### ISSUE TITLE
On Hover right arrow get's a little bit of the element background color

### ISSUE THREAD

**Issue by brunogaspar** [komputerwiz/css3-breadcrumbs#2]
Hi,

I'm having a little issue, not sure if it is easy to fix or not and/or maybe i managed to break the css...

The issue is this ( it is zoomed in )
http://d.pr/i/DrlZ

When a crumb is hovered the arrow on the right get's a little bit of the background

Here is the css i have http://jsfiddle.net/BMqtL/ ( i modified it a bit )

Regards

**Comment by komputerwiz** [comment]
I'm so sorry it's taken this long for me to get to this.

The issue is due to the modifications and require a little extra tweaking: The arrow thingy just needs to be translated up to compensate for the thicker borders (ideally 1.5px, but I just rounded up to 2px):

``` css
/* lines 71–90 */
.breadcrumbs2 ul li a:after, .breadcrumbs2 ul li span:after {
    /* ... */
    top: -2px;
    /* ... */
}
```
